<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.tjetc</groupId>
    <artifactId>medical-imaging-system</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <modules>
        <module>imms-service</module>
        <module>imms-common</module>
        <module>imms-dal</module>
        <module>imms-api</module>
        <module>imms-boot-web</module>
        <module>imms-boot-harmony</module>
    </modules>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.3</version> <relativePath></relativePath>
    </parent>
    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <revision>1.0.0.0</revision>
        <mybatis-plus-spring-boot3-starter.version>3.5.7</mybatis-plus-spring-boot3-starter.version>

        <commons-lang3.version>3.18.0</commons-lang3.version>
        <jjwt.version>0.12.5</jjwt.version>
        <kaptcha.version>2.3.2</kaptcha.version>

        <google.genai.version>0.4.0</google.genai.version>
        <imms-dal.version>1.0.0.0</imms-dal.version>
        <imms-common.version>1.0.0.0</imms-common.version>
        <imms-service.version>1.0.0.0</imms-service.version>
        <imms-api.version>1.0.0.0</imms-api.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.google.genai</groupId>
                <artifactId>google-genai</artifactId>
                <version>${google.genai.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus-spring-boot3-starter.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${commons-lang3.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>com.tjetc</groupId>
                <artifactId>imms-dal</artifactId>
                <version>${imms-dal.version}</version>
            </dependency>
            <dependency>
                <groupId>com.tjetc</groupId>
                <artifactId>imms-common</artifactId>
                <version>${imms-common.version}</version>
            </dependency>
            <dependency>
                <groupId>com.tjetc</groupId>
                <artifactId>imms-service</artifactId>
                <version>${imms-service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.tjetc</groupId>
                <artifactId>imms-api</artifactId>
                <version>${imms-api.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.penggle</groupId>
                <artifactId>kaptcha</artifactId>
                <version>${kaptcha.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>